CREATE DATABASE STORED_PROCEDURES;
USE STORED_PROCEDURES;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    email VARCHAR(100)
);

DELIMITER $$
CREATE PROCEDURE InsertUser(IN p_name VARCHAR(100), IN p_email VARCHAR(100))
BEGIN 
INSERT INTO USERS(name, email) VALUES(p_name,p_email);
END $$

DELIMITER ;

DELIMITER $$
CREATE PROCEDURE GetUserById(IN p_id INT)
BEGIN 
SELECT * FROM USERS WHERE ID = p_id;
END $$

DELIMITER ;

DELIMITER $$
CREATE PROCEDURE UpdateUser(IN p_id INT,IN p_name VARCHAR(100),IN p_email VARCHAR(100))
BEGIN
UPDATE USERS SET name = p_name, email = p_email WHERE id = p_id ;
END $$

DELIMITER ;

DELIMITER $$
CREATE PROCEDURE DeleteUser(IN p_id INT)
BEGIN
DELETE FROM USERS WHERE id = p_id;
END $$

DELIMITER ;
